import React from 'react';
import Icon from '../components/Icon';

export default function Landing({ onAuth, onDemo }) {
  return <main className="landing">
    <nav className="landing-nav"><a className="brand" href="#top"><span className="brand-mark"><Icon name="spark"/></span><b>PlanYour<span>Fit</span></b></a><div className="landing-links"><a href="#funkcje">Funkcje</a><a href="#jak-dziala">Jak to działa</a></div><div className="landing-actions"><button className="ghost-button" onClick={() => onAuth('login')}>Zaloguj się</button><button className="primary-button compact" onClick={() => onAuth('register')}>Załóż konto</button></div></nav>
    <section className="hero" id="top"><div className="hero-copy"><div className="hero-badge"><Icon name="spark" size={15}/> Twój ruch. Twój rytm.</div><h1>Plan treningowy,<br/>który <em>zna pogodę.</em></h1><p>Zaplanuj aktywność, sprawdź warunki i odkryj najlepsze miejsca w pobliżu. Wszystko w jednym, spokojnym rytmie.</p><div className="hero-actions"><button className="primary-button large" onClick={onDemo}>Wypróbuj demo <Icon name="arrow"/></button><button className="play-button" onClick={() => document.getElementById('jak-dziala')?.scrollIntoView({ behavior: 'smooth' })}><span>▶</span> Zobacz jak działa</button></div><div className="hero-proof"><div className="avatar-stack"><span>MK</span><span>AL</span><span>JS</span></div><div><b>4,9 <span>★★★★★</span></b><small>Planuj mądrzej, ruszaj się częściej</small></div></div></div>
      <div className="hero-visual"><div className="visual-orbit orbit-one"/><div className="visual-orbit orbit-two"/><div className="runner-card"><div className="runner-sun"/><div className="runner-figure"><span className="head"/><span className="body"/><span className="arm a"/><span className="arm b"/><span className="leg a"/><span className="leg b"/></div><div className="runner-shadow"/><div className="weather-float"><Icon name="sun"/><span><b>18°C</b><small>Idealne warunki</small></span></div><div className="distance-float"><Icon name="route"/><span><b>7,2 km</b><small>Trasa gotowa</small></span></div></div></div>
    </section>
    <section className="feature-section" id="funkcje"><span className="section-kicker">MNIEJ ZGADYWANIA, WIĘCEJ RUCHU</span><h2>Wszystko, czego potrzebuje<br/>Twój aktywny tydzień.</h2><div className="feature-grid"><article><span className="feature-number">01</span><span className="feature-icon lime"><Icon name="calendar"/></span><h3>Inteligentny kalendarz</h3><p>Planuj treningi w widoku miesiąca, tygodnia lub dnia. Bez chaosu.</p></article><article><span className="feature-number">02</span><span className="feature-icon orange"><Icon name="cloud"/></span><h3>Pogoda pod kontrolą</h3><p>Sprawdzamy temperaturę, wiatr i opady dokładnie na godzinę treningu.</p></article><article><span className="feature-number">03</span><span className="feature-icon blue"><Icon name="route"/></span><h3>Trasy i miejsca</h3><p>Znajdź trasę biegową, halę lub basen w wybranym promieniu.</p></article></div></section>
    <section className="steps-section" id="jak-dziala"><div><span className="section-kicker">TO NAPRAWDĘ PROSTE</span><h2>Od pomysłu do treningu<br/>w trzech krokach.</h2></div><ol><li><span>1</span><div><b>Wybierz aktywność</b><p>Bieganie, koszykówka lub pływanie.</p></div></li><li><span>2</span><div><b>Dodaj czas i miejsce</b><p>Resztę sprawdzimy za Ciebie.</p></div></li><li><span>3</span><div><b>Ruszaj!</b><p>Z trasą, pogodą i dobrym planem.</p></div></li></ol></section>
    <footer><a className="brand" href="#top"><span className="brand-mark"><Icon name="spark"/></span><b>PlanYour<span>Fit</span></b></a><p>Ruch dobrze zaplanowany.</p><small>© {new Date().getFullYear()} PlanYourFit</small></footer>
  </main>;
}
