import React, { useState } from 'react';
import Icon from '../components/Icon';
import { api } from '../api';

export default function Settings({ user, theme, setTheme, demo, notify, onUserChange }) {
  const [form, setForm] = useState({ name: user.name, email: user.email, defaultLocation: user.defaultLocation || '', preferredRadiusKm: user.preferredRadiusKm || 10, theme });
  const [password, setPassword] = useState({ currentPassword: '', newPassword: '' });
  const [busy, setBusy] = useState(false);
  const set = (key, value) => setForm((current) => ({ ...current, [key]: value }));
  const save = async (e) => { e.preventDefault(); setBusy(true); try { if (!demo) await api.updateProfile(form); onUserChange({ ...user, ...form }); setTheme(form.theme); notify('Ustawienia zostały zapisane.', 'success'); } catch (error) { notify(error.message, 'error'); } finally { setBusy(false); } };
  const changePassword = async (e) => { e.preventDefault(); if (password.newPassword.length < 8) return notify('Nowe hasło musi mieć co najmniej 8 znaków.', 'error'); setBusy(true); try { if (!demo) await api.changePassword(password); setPassword({ currentPassword:'',newPassword:'' }); notify('Hasło zostało zmienione.', 'success'); } catch (error) { notify(error.message, 'error'); } finally { setBusy(false); } };
  return <div className="settings-page"><header className="page-intro"><div><span className="eyebrow">TWOJE PREFERENCJE</span><h1>Ustawienia</h1><p>Dopasuj PlanYourFit do swojego rytmu.</p></div></header><div className="settings-layout"><nav className="settings-nav"><button className="active"><Icon name="user"/> Profil</button><button><Icon name="pin"/> Lokalizacja</button><button><Icon name="moon"/> Wygląd</button><button><Icon name="bell"/> Powiadomienia</button></nav><div className="settings-main">
    <form className="card settings-card" onSubmit={save}><div className="settings-heading"><span className="profile-avatar">{user.name.slice(0,2).toUpperCase()}</span><div><h2>Dane profilu</h2><p>Podstawowe informacje o Twoim koncie.</p></div></div><div className="form-grid"><label className="field"><span>Imię</span><input value={form.name} onChange={(e)=>set('name',e.target.value)} required/></label><label className="field"><span>E-mail</span><input type="email" value={form.email} onChange={(e)=>set('email',e.target.value)} required/></label><label className="field span-2"><span>Domyślna lokalizacja</span><div className="field-with-icon"><Icon name="pin"/><input value={form.defaultLocation} onChange={(e)=>set('defaultLocation',e.target.value)} placeholder="Np. Warszawa"/></div></label><label className="field"><span>Domyślny promień</span><div className="input-suffix"><input type="number" min="1" max="50" value={form.preferredRadiusKm} onChange={(e)=>set('preferredRadiusKm',e.target.value)}/><b>km</b></div></label></div><div className="theme-setting"><span>Motyw aplikacji</span><div className="theme-options">{[['light','Jasny','sun'],['dark','Ciemny','moon'],['system','Systemowy','settings']].map(([value,label,icon])=><button type="button" key={value} className={form.theme===value?'active':''} onClick={()=>set('theme',value)}><Icon name={icon}/><b>{label}</b>{form.theme===value&&<Icon name="check" size={15}/>}</button>)}</div></div><div className="settings-footer"><button className="primary-button" disabled={busy}>{busy?'Zapisuję…':'Zapisz ustawienia'}</button></div></form>
    <form className="card settings-card compact-card" onSubmit={changePassword}><div className="settings-heading"><span className="settings-symbol">•••</span><div><h2>Bezpieczeństwo</h2><p>Zmień hasło do swojego konta.</p></div></div><div className="form-grid"><label className="field"><span>Obecne hasło</span><input type="password" value={password.currentPassword} onChange={(e)=>setPassword({...password,currentPassword:e.target.value})}/></label><label className="field"><span>Nowe hasło</span><input type="password" minLength="8" value={password.newPassword} onChange={(e)=>setPassword({...password,newPassword:e.target.value})}/></label></div><div className="settings-footer"><button className="secondary-button" disabled={busy}>Zmień hasło</button></div></form>
  </div></div></div>;
}
